### ISSUE TITLE
Review comments

### ISSUE THREAD

**Issue by ghost** [rizualam/reverse#1]
1. Why is stdlib used, when you are not calling any of its functions
2. Accept the input from command line arguments
3. why is the 3rd variable(temp) used to swap the characters, can you swap chars without using 3rd variable
4. input validation missing

**Comment by rizualam** [comment]
#include <stdio.h>
#include <string.h>
int main( int argc, char *argv[])
{
    char a[20];
    int i=0,len,mid;
    printf("please enter the string\n");
    scanf("%s",a);
    len=strlen(a);
    mid=len/2;
    while(i<mid)
    {
        a[i]=a[i]^a[len-1-i];
        a[len-1-i]=a[len-1-i]^a[i];
        a[i]=a[i]^a[len-1-i];
        i++;
    }
    puts(a);
    return 0;
}

**Comment by rizualam** [comment]
#include <stdio.h>
#include <string.h>

int main( int argc, char *argv[] )  {
   if( argc == 2 ) {
      printf("%s\n", argv[1]);
      int i=0,len,mid;
      len=strlen(argv[1]);
      mid=len/2;
      while(i<mid)
      {
        argv[1][i]=argv[1][i]^argv[1][len-1-i];
        argv[1][len-1-i]=argv[1][len-1-i]^argv[1][i];
        argv[1][i]=argv[1][i]^argv[1][len-1-i];
        i++;
}
puts(argv[1]);

   }
   else if( argc > 2 ) {
      printf("Too many arguments supplied.\n");
   }
   else {
      printf("One argument expected.\n");
      printf("%s",argv[0]);
   }
}

**Comment by rizualam** [comment]
#include <stdio.h>
#include <string.h>

int main( int argc, char *argv[] )  {
   if( argc == 2 ) {
      char *a;
      int i=0,len,mid;
      a=strdup(argv[1]);
      len=strlen(a);
      mid=len/2;
      while(i<mid)
      {
        a[i]=a[i]^a[len-1-i];
        a[len-1-i]=a[len-1-i]^a[i];
        a[i]=a[i]^a[len-1-i];
        i++;
      }
      puts(a);

   }
   else if( argc > 2 ) {
      printf("Too many arguments supplied.\n");
   }
   else {
      printf("One argument expected.\n");
      printf("%s",argv[0]);
   }
}

**Comment by ghost** [comment]
sounds good.
